name: Update Hosts

on:
  schedule:
    - cron: "0 * * * *"
      timezone: "Asia/Shanghai"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Verify files
      run: |
        pwd
        ls -la
        cat requirements.txt
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run updater
      run: |
        export PYTHONPATH=$GITHUB_WORKSPACE
        python -m hosts_generator.main
        
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add hosts.txt
        git commit -m "Update hosts.txt [skip ci]" || echo "No changes to commit"
        git push
