name: Update Hosts

on:
  schedule:
    # 北京时间每小时运行一次（UTC+8）
    - cron: "0 * * * *"
      timezone: "Asia/Shanghai"
  workflow_dispatch:  # 支持手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: sudo apt-get install -y libxml2-dev libxslt-dev python3-dev
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run updater
      run: |
        export PYTHONPATH=$GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        python src/main.py
        
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add hosts.txt
        git diff --quiet && git diff --staged --quiet || git commit -m "Update hosts.txt [skip ci]"
        git push
