name: Update Hosts

on:
  schedule:
    # 北京时间每小时运行一次（UTC+8）
    - cron: "0 * * * *"
      timezone: "Asia/Shanghai"
  workflow_dispatch:  # 支持手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        # 先进入项目根目录
        cd ${{ github.workspace }}
        pip install pythonping requests aiodns retry beautifulsoup4
        
    - name: Run updater
    run: |
      # 添加项目根目录到PYTHONPATH
      export PYTHONPATH=$GITHUB_WORKSPACE
      cd $GITHUB_WORKSPACE
      python -m hosts_generator.main
        
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add hosts.txt
        git commit -m "Update hosts.txt [skip ci]" || echo "No changes to commit"
        git push
